language: java
jdk: openjdk11

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

addons:
  sonarcloud:
    organization: "project-quatum"
    token:
      secure: "nkh/0MKQdVVPN92Z2iZC2aD2nn2MfqlQJnXtLuJktmPbxbVF9t3Bogk7Z24aE4k6/n8skHfLhLsy2Xkga8y/KQVOguJgdxoUnpMgcJgvN0p1WHb01R6lLzCjvqOLrW6xvvYamnCiHUxq29kbQKHZA21/awhaK+3S7gG23V4V4dzXttT7Vvf4/aqyKLzg0urltYhI+0z0qgLx2YzuIPNDmgVJnn30WOGRJK7+VprWuaZ9WH15sfvCO6HUF/yGubvHzZM8hRUHn7542v5Y02T/bGygIHIqPgYSqJ0tK7M+PjbfRyBmSDyNT7fzlXfcBrfZeAO0aQd2lpInfnTE3Ft0m419/AiXORUdrXo0iiWNIwTKXkIZbULa2gcynNLtJu1RphfY2FqdEGHzrOmPJmABRvdpZzu/pWHLjhgX4wioVKSt1jkZSvPnCLsfoowxz+WMHv5VjmP50rN8G9f+w569rYGMhItEeNlnHW9gAR8YjpAKskJerOC9X6Yyd+mj+nlHw80cN44LLIn8/6bxz6BoF6D77bxEiYPasswBRZIQBgyMBJ3QAk7PRNIDcN203suDmssiNVY+EZQmjQePhR1nlb5qqcK0vDBp/7GZNmP8i+YIi8IZXtwMWkosrTSLn/nH/JmZZtF3VR1p46wuD5+p9bwLG19drt5JOVXuNpX8c/Y=" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar -Dsonar.login=$AuthToken -Dsonar.projectKey=Project-Quatum_Project-Quantum -DskipTests
